### ISSUE TITLE
Example usage does not work

### ISSUE THREAD

**Issue by maximebrunet** [mc-rtc/mc-rtc-superbuild#1]
Hello @gergondet,

I just tried to use this project, but, when I launched the command ` cmake -S mc-rtc-superbuild -B .`, I got the error

```
E: The repository 'https://dl.bintray.com/gergondet/multi-contact-head bionic Release' does not have a Release file.
```

Is the repository down ? or does it not have a bionic Release file ?

Thanks a lot for your help,
Maxime

**Comment by maximebrunet** [comment]
I just noticed I had the error 

```
Err:5 https://dl.bintray.com/gergondet/multi-contact-head bionic Release
  Could not handshake: The TLS connection was non-properly terminated.
```

So I tried using rather `http://dl.bintray.com/gergondet/multi-contact-head` and it worked !

**Comment by gergondet** [comment]
Hi @maximebrunet 

There's no more bintray mirror and you should probably remove it from your APT sources.

I'll close this issue but feel free to re-open if you encounter other build issues.

**Comment by maximebrunet** [comment]
Thank you @gergondet for your answer ! 

Indeed, I don't know how I added this repo, but it's not required. 

I am currently playing out with `lipm_walking_controller` and trying to get one of its fork to work, must have left this one behind (probably from `stephane-caron/lipm_walking_controller`).

By the way, I opened issues in `mc_openrtm` (and `mc_rtc` just in case you don't check `mc_openrtm` not so often) regarding my attempt to launch the lipm walking controller in chorenoid, could you have a look at it please ?

Thanks a lot,
Maxime
