### ISSUE TITLE
mc_udp automatically requires gite.lirmm access

### ISSUE THREAD

**Issue by tabinohito** [mc-rtc/mc-rtc-superbuild#10]
Hello, I'm a new Japanese visitor student at JRL.
When I use mc-rtc-superbuild , I could not read from 'git@gite.lirmm.fr:choreonoid-hrp-installation/hrp-choreonoid'.
It would be great if we could add the mc_udp select option.
Thanks in advance.

**Comment by gergondet** [comment]
I have setup a mirror on isri-aist Github and drcutil-superbuild is now using that mirror when using isri-aist as a private remote (default)
