### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by tabinohito** [mc-rtc/mc-rtc-superbuild#18]
When I tried to install on user directory (on Ubuntu20.04),
I faced this error.

I configured as like this:
cmake --build mc-rtc-superbuild/build --config RelWithDebInfo

```
--------------------------------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------------------------------
[build] Error: The file ~/src/rhps1/generate_robot_description/robot_description_template/package.xml is an invalid package.xml file. See below for details:

Package name "@ROBOT_DESCRIPTION_NAME@" does not follow naming conventions
Package version "@ROBOT_DESCRIPTION_VERSION@" does not follow version conventions
Invalid email "@ROBOT_DESCRIPTION_MAINTAINER_EMAIL@" for person "@ROBOT_DESCRIPTION_MAINTAINER_NAME@"
CMake Error at /home/tako/src/mc-rtc-superbuild/cmake/scripts/cmake-with-prefix.cmake:20 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"
```

**Comment by gergondet** [comment]
Hi @tabinohito 

Did you solve this? I don't think the RHPS1 package is meant to be built in a catkin workspace but I'm not sure why it's trying to in the first place

**Comment by tabinohito** [comment]
The problem was temporarily resolved, but has recurred.
I am currently trying to UPDATE mc-rtc to 2.4.0.
At that time, I am getting an error because it tries to build my other source code on its own.
So, is there any way to specify a folder to ignore it?

**Comment by gergondet** [comment]
> So, is there any way to specify a folder to ignore it?

superbuild does not build anything it doesn't explicitly control except if you add packages in a catkin workspace it thinks it controls

**Comment by tabinohito** [comment]
When I try to build a Baseline Walking Controller, I get an error because the qp solver is built without being specified. 
```
- ENABLE_QLD: OFF
- ENABLE_QUADPROG: OFF
- ENABLE_LSSOL: OFF
- ENABLE_JRLQP: OFF
- ENABLE_QPOASES: OFF
- ENABLE_OSQP: OFF
- ENABLE_NASOQ: OFF
- ENABLE_HPIPM: OFF
- ENABLE_PROXQP: OFF
- ENABLE_QPMAD: OFF
CMake Error at CMakeLists.txt:95 (message):
  None of the QP solvers are enabled.  Enable at least one QP solver.
```

This error occurs when using the cmake argument to configure the settings.

So what should I do in these cases?

**Comment by gergondet** [comment]
Hi @tabinohito 

Are you using https://github.com/mc-rtc/superbuild-extensions to add `BaselineWalkingController` to your build? This should enable all solvers (except LSSOL optionally)

**Comment by tabinohito** [comment]
Thank　you!
I was able to resolve this problem.
