### ISSUE TITLE
Cmake error from choreonoid-openrtm

### ISSUE THREAD

**Issue by tabinohito** [mc-rtc/mc-rtc-superbuild#19]
Using Ubuntu20.04 and [ana-avater-controller-superbuild](https://github.com/isri-aist/ana-avatar-controller-superbuild).
I faced this error.
![Screenshot from 2023-05-12 15-32-40](https://github.com/mc-rtc/mc-rtc-superbuild/assets/29534522/411273eb-1703-456c-b13c-bbb09fe9ea25)

It is same problem of [this one](https://stackoverflow.com/questions/59522267/cmake-rejects-a-second-target-link-libraries-talking-about-keyword-vs-plain).

Which description is correct to match?

**Comment by gergondet** [comment]
Hi @tabinohito 

This seems related to a recent change in Choreonoid (https://github.com/choreonoid/choreonoid/commit/5a1dbbfad83f9bc677761c3915e5a4614d559183) and we need to update all our Choreonoid extensions accordingly. In the meantime I think you can checkout a version of Choroenoid that predates this latest one.

**Comment by gergondet** [comment]
The plugins should now work with the latest version of Choreonoid but this is pending on two PRs being merged
