### ISSUE TITLE
Observations of my first trials

### ISSUE THREAD

**Issue by arntanguy** [mc-rtc/mc-rtc-superbuild#2]
I've been experimenting with using mc-rtc-superbuild, and in particular extensions to handle all projects, and I've found some issues and pitfalls with it. I should have reported them as they appeared as it's now a bit blurry. Overall:

- Sometimes it recompiles python bindings for mc_rtc and all its dependencies for no apparent reason, which obviously takes forever ;)
- Sometimes projects do not get recompiled even though there are changes to them (experienced in particular when working on mc_ana_avatar_controller). Building the project explicitely from `~/devel/build` does pick up these changes
- It's not trivial to figure out how to change the layout of sources folders. For instance I originally had the lipm-walking-superbuild and the ana-avatar-controller-superbuild, and decided to remove the lipm-walking-superbuild and add lipm-walking to the ana-avatar-controller-superbuild instead (as it needs a very specific branch). Doing this, the superbuild kept trying to build the old lipm-walking-superbuild extension and never pulled the new repository. I suspect this might be because the folder structure gets flattened in mc-rtc-superbuild/build and thus sub-folders containing the same projects (e.g ana/lipm_walking/lipm_walking_controller and lipm_walking/lipm_walking_controller) get mixed up together.
- It's not clear what would happen if two extensions had the same dependency (e.g lipm-walking-superbuild and ana-avatar-controller-superbuild both wanting to install the lipm_walking_controller)
- I had some (newbie) unexpected results trying to force the superbuild script to rebuild projects by removing build prefix files. Notably if you do remove the build/prefix/<project> folder it will clone the project over whichever source files existed, thus deleting local changes. This is obviously a misuse of the system on my end, but still a quite violent result ;)
- Manually deleting a folder in `~/devel/build` does not result in it being recreated and the project recompiled.
- Udpate mechanism: for now we need to pull each project manually to update? I preferred the previous `build_and_install script` behavior that would pull upstream changes when there was no local change, and prompts the user to take action when local changes were present.

Overall I think it's much harder to have a clear view of what happens exactly in the build process. But I think that mostly comes down to not being used to the system.

I'll try to report more detailed cases as they happen here ;)

**Comment by gergondet** [comment]
Hi Arnaud,

Thanks for the detailed feedback.

> Sometimes it recompiles python bindings for mc_rtc and all its dependencies for no apparent reason, which obviously takes forever ;)

I think this can happen if you updated mc-rtc-superbuild as I changed some of the commands used to build projects and that will trigger re-builds. I don't think it should happen in general.

> Sometimes projects do not get recompiled even though there are changes to them (experienced in particular when working on mc_ana_avatar_controller). Building the project explicitely from ~/devel/build does pick up these changes

That is definitely not expected and I will try to reproduce. The way it is supposed to work is that we setup a monitor on the source repository so that any files under source control that is changed will trigger a configure (and subsequently let CMake/Ninja figure out what needs to be rebuilt).

> It's not clear what would happen if two extensions had the same dependency (e.g lipm-walking-superbuild and ana-avatar-controller-superbuild both wanting to install the lipm_walking_controller)

(I skipped the previous point because it is related). The way it currently works is that if two extensions declare the same project (the `SUBFOLDER` is irrelevant project-wise) then only one of the two (whichever was included first) will build. We should consider it is a conflict and emit a fatal errror if the same project is specified with different origin and/or branch and let the user figure which extension he should trust then (I think) the user would have to nuke the corresponding project folder under the build/prefix directory.

> I had some (newbie) unexpected results trying to force the superbuild script to rebuild projects by removing build prefix files. Notably if you do remove the build/prefix/ folder it will clone the project over whichever source files existed, thus deleting local changes. This is obviously a misuse of the system on my end, but still a quite violent result ;)

Yes. I think unfortunately the same thing happens if you change the remote or branch (basically CMake will nuke your existing source folder). I will check if there is some way to work around this behaviour.

You almost got it right though as you can force some steps by removing specific files under the prefix folder. For example, removing `prefix/mc_ana_avatar_controller/src/mc_ana_avatar_controller-stamp/mc_ana_avatar_controller-configure` will force it to re-run the configure step and all subsequent steps.

> Manually deleting a folder in ~/devel/build does not result in it being recreated and the project recompiled.

Yup. Only the stamps (and source changes) matter so to force a build you have to remove the right stamp.

> Udpate mechanism: for now we need to pull each project manually to update? 

For now yes. Handling updates in mc-rtc-superbuild has been on my todo list for a few weeks now though :s The plan is to use the update strategy that we were using in build_and_install.sh (pull if no changes, leave it as-is and let the user figure it out otherwise)

**Comment by arntanguy** [comment]
> I think unfortunately the same thing happens if you change the remote or branch (basically CMake will nuke your existing source folder)

Thanks for the warning, that could definitely have happened. Any way to prevent that from happening? I could see it being quite dangerous.

**Comment by mmurooka** [comment]
@gergondet Thanks for maintaining the installation framework. Let me add my feedback as well.

It is not clear how to clone/build/install only a part of all packages. For example, let's say that you have finished a complete build using only mc-rtc-superbuild, and then you need LIPMWalkingController, so you add lipm-walking-controller-superbuild to your extensions. In this case, I don't know how to build only the newly required packages with lipm-walking-controller-superbuild, without touching the packages already installed with mc-rtc-superbuild.
Doing `cmake .. && cmake --build .` in `mc-rtc-superbuild/build` will build all packages in mc-rtc-superbuild and lipm-walking-controller-superbuild combined.

**Comment by gergondet** [comment]
In general you can do:
```
cmake --build . --target lipm_walking_controller
```

To build a project. However, this also builds every dependencies of that project as needed.

> Doing cmake .. && cmake --build . in mc-rtc-superbuild/build will build all packages in mc-rtc-superbuild and lipm-walking-controller-superbuild combined

@mmurooka that shouldn't happen but it might, allow me to explain

The way it's supposed to work:
- sources in the cloned folder are monitored via the source-monitor script (https://github.com/mc-rtc/mc-rtc-superbuild/blob/main/cmake/scripts/source-monitor.cmake)
- if a change is detected in a project (solely based on files, timestamps and gitignore) the project is reconfigured. This automatically triggers a configure/build/install step for every dependent projects

In practice however, it seems the script evaluates some files it shouldn't and sometimes see changes that should not exist. The next time it happens (and you are pretty confident that it shouldn't), can you check:
- the project that triggered a rebuild (you will get a cmake message: `--- Will rebuild ${PROJECT} because...`
- send me these files:
```
prefix/mc_rtc/src/mc_rtc-stamp/mc_rtc-source-monitor.sources
prefix/mc_rtc/src/mc_rtc-stamp/mc_rtc-source-monitor.sources.before
prefix/mc_rtc/src/mc_rtc-stamp/mc_rtc-source-monitor.timestamps
prefix/mc_rtc/src/mc_rtc-stamp/mc_rtc-source-monitor.timestamps.before
```
(where the prefix folder is found in the build folder of superbuild and mc_rtc should be replaced with the project's name that triggered the rebuild)

**Comment by mitsuharu-morisawa** [comment]
Hi, @gergondet , when I ran mc-rtc-superbuild on ubuntu 18.04,
I faced following error at SpaceVecAlg/tests.
How can I fixed this problem ?

--------------------------------------------------
--------------------------------------------------
[  5%] Performing test step for 'SpaceVecAlg'
Test project /home/morisawa/workspace/build/SpaceVecAlg
    Start 1: VectorTestUnit
1/7 Test #1: VectorTestUnit ...................   Passed    0.00 sec
    Start 2: InertiaTestUnit
2/7 Test #2: InertiaTestUnit ..................   Passed    0.00 sec
    Start 3: PTransformTestUnit
3/7 Test #3: PTransformTestUnit ...............   Passed    0.09 sec
    Start 4: AutoDiffTestUnit
4/7 Test #4: AutoDiffTestUnit .................   Passed    0.00 sec
    Start 5: ConversionsTestUnit
5/7 Test #5: ConversionsTestUnit ..............   Passed    0.00 sec
    Start 6: LogDiffTestUnit
6/7 Test #6: LogDiffTestUnit ..................   Passed    0.01 sec
    Start 7: test-sva-python3-bindings
7/7 Test #7: test-sva-python3-bindings ........***Failed    0.12 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) =   0.24 sec

The following tests FAILED:
	  7 - test-sva-python3-bindings (Failed)
Errors while running CTest
Output from these tests are in: /home/morisawa/workspace/build/SpaceVecAlg/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
CMakeFiles/SpaceVecAlg.dir/build.make:115: recipe for target 'prefix/SpaceVecAlg/src/SpaceVecAlg-stamp/SpaceVecAlg-test' failed
make[2]: *** [prefix/SpaceVecAlg/src/SpaceVecAlg-stamp/SpaceVecAlg-test] Error 8
CMakeFiles/Makefile2:1134: recipe for target 'CMakeFiles/SpaceVecAlg.dir/all' failed
make[1]: *** [CMakeFiles/SpaceVecAlg.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
---------------------------------------------------------
---------------------------------------------------------


/home/morisawa/workspace/build/SpaceVecAlg/Testing/Temporary/LastTest.log
Start testing: Jan 11 17:43 JST
----------------------------------------------------------
1/7 Testing: VectorTestUnit
1/7 Test: VectorTestUnit
Command: "/home/morisawa/workspace/build/SpaceVecAlg/tests/VectorTest"
Directory: /home/morisawa/workspace/build/SpaceVecAlg/tests
"VectorTestUnit" start time: Jan 11 17:43 JST
Output:
----------------------------------------------------------
Running 5 test cases...

*** No errors detected
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"VectorTestUnit" end time: Jan 11 17:43 JST
"VectorTestUnit" time elapsed: 00:00:00
----------------------------------------------------------

2/7 Testing: InertiaTestUnit
2/7 Test: InertiaTestUnit
Command: "/home/morisawa/workspace/build/SpaceVecAlg/tests/InertiaTest"
Directory: /home/morisawa/workspace/build/SpaceVecAlg/tests
"InertiaTestUnit" start time: Jan 11 17:43 JST
Output:
----------------------------------------------------------
Running 4 test cases...

*** No errors detected
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"InertiaTestUnit" end time: Jan 11 17:43 JST
"InertiaTestUnit" time elapsed: 00:00:00
----------------------------------------------------------

3/7 Testing: PTransformTestUnit
3/7 Test: PTransformTestUnit
Command: "/home/morisawa/workspace/build/SpaceVecAlg/tests/PTransformTest"
Directory: /home/morisawa/workspace/build/SpaceVecAlg/tests
"PTransformTestUnit" start time: Jan 11 17:43 JST
Output:
----------------------------------------------------------
Running 10 test cases...

*** No errors detected
<end of output>
Test time =   0.09 sec
----------------------------------------------------------
Test Passed.
"PTransformTestUnit" end time: Jan 11 17:43 JST
"PTransformTestUnit" time elapsed: 00:00:00
----------------------------------------------------------

4/7 Testing: AutoDiffTestUnit
4/7 Test: AutoDiffTestUnit
Command: "/home/morisawa/workspace/build/SpaceVecAlg/tests/AutoDiffTest"
Directory: /home/morisawa/workspace/build/SpaceVecAlg/tests
"AutoDiffTestUnit" start time: Jan 11 17:43 JST
Output:
----------------------------------------------------------
Running 1 test case...
0 0
2 0
0 0

0 0
1 0
0 0

-0.707107 -0.707107
 0.707107 -0.707107
0 0


*** No errors detected
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"AutoDiffTestUnit" end time: Jan 11 17:43 JST
"AutoDiffTestUnit" time elapsed: 00:00:00
----------------------------------------------------------

5/7 Testing: ConversionsTestUnit
5/7 Test: ConversionsTestUnit
Command: "/home/morisawa/workspace/build/SpaceVecAlg/tests/ConversionsTest"
Directory: /home/morisawa/workspace/build/SpaceVecAlg/tests
"ConversionsTestUnit" start time: Jan 11 17:43 JST
Output:
----------------------------------------------------------
Running 2 test cases...
 13.0208 -2.94975       10
 13.0208 -2.94975       10

*** No errors detected
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"ConversionsTestUnit" end time: Jan 11 17:43 JST
"ConversionsTestUnit" time elapsed: 00:00:00
----------------------------------------------------------

6/7 Testing: LogDiffTestUnit
6/7 Test: LogDiffTestUnit
Command: "/home/morisawa/workspace/build/SpaceVecAlg/tests/LogDiffTest"
Directory: /home/morisawa/workspace/build/SpaceVecAlg/tests
"LogDiffTestUnit" start time: Jan 11 17:43 JST
Output:
----------------------------------------------------------
Running 5 test cases...

*** No errors detected
<end of output>
Test time =   0.01 sec
----------------------------------------------------------
Test Passed.
"LogDiffTestUnit" end time: Jan 11 17:43 JST
"LogDiffTestUnit" time elapsed: 00:00:00
----------------------------------------------------------

7/7 Testing: test-sva-python3-bindings
7/7 Test: test-sva-python3-bindings
Command: "/home/morisawa/.local/lib/python3.6/site-packages/cmake/data/bin/cmake" "-E" "env" "LD_LIBRARY_PATH=/home/morisawa/workspace/src/catkin_ws/devel/lib:/home/morisawa/workspace/src/catkin_data_ws/devel/lib:/home/morisawa/workspace/openrtp/lib:/opt/ros/melodic/share/euslisp/jskeus/eus//Linux64/lib:/opt/ros/melodic/lib" "/home/morisawa/.local/lib/python3.6/site-packages/cmake/data/bin/cmake" "-E" "env" "PYTHONPATH=.:/home/morisawa/workspace/src/catkin_ws/devel/lib/python2.7/dist-packages:/home/morisawa/workspace/src/catkin_data_ws/devel/lib/python2.7/dist-packages:/home/morisawa/workspace/openrtp/lib/python3.6/site-packages:/home/morisawa/workspace/openrtp/lib/python3.6/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages" "/home/morisawa/.local/lib/python3.6/site-packages/cmake/data/bin/cmake" "-E" "chdir" "/home/morisawa/workspace/build/SpaceVecAlg/binding/python/sva/python3/RelWithDebInfo" "python3" "-m" "pytest"
Directory: /home/morisawa/workspace/build/SpaceVecAlg/binding/python
"test-sva-python3-bindings" start time: Jan 11 17:43 JST
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/usr/lib/python3/dist-packages/_pytest/fixtures.py", line 842, in <module>
    class FixtureFunctionMarker(object):
  File "/usr/lib/python3/dist-packages/_pytest/fixtures.py", line 844, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'
<end of output>
Test time =   0.11 sec
----------------------------------------------------------
Test Failed.
"test-sva-python3-bindings" end time: Jan 11 17:43 JST
"test-sva-python3-bindings" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Jan 11 17:43 JST

**Comment by gergondet** [comment]
Hi @mitsuharu-morisawa 

I have never seens this error, could you check the following two commands:
```
python3 -m pip list --format=columns|grep attrs
python3 -m pip list --format=columns|grep pytest
```

In a Ubuntu 18.04 docker, using the APT packages for those Python packages, I get:
```
attrs              17.4.0
pytest             3.3.2
```

**Comment by mitsuharu-morisawa** [comment]
@gergondet  Thank you very much for your advice.

attrs was installed newer version in my PC.
```
python3 -m pip list --format=columns| grep attrs
attrs                      20.3.0
morisawa@moury-ThinkPad-P52:~$ python3 -m pip list --format=columns| grep pytest
pytest                     3.3.2
```
So I downgrade attrs
`pip install attrs==17.4.0`

Then installation have been succeeded.

**Comment by mitsuharu-morisawa** [comment]
@gergondet, sorry for my question, again.
I faced catkin will make the directories under home directory.
How can I set this directory ?

```
Build catkin workspace mc_rtc_ws at /home/morisawa/workspace/src/catkin_ws
--------------------------------------------------------------------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /home/morisawa/workspace/src/catkin_ws/devel:/home/morisawa/workspace/src/catkin_data_ws/devel:/opt/ros/melodic
Workspace:                   /home/morisawa
--------------------------------------------------------------------------------------------------------------------------------------
Build Space:        [exists] /home/morisawa/build
Devel Space:        [exists] /home/morisawa/devel
Install Space:      [unused] /home/morisawa/install
Log Space:         [missing] /home/morisawa/logs
Source Space:       [exists] /home/morisawa/src
DESTDIR:            [unused] None
--------------------------------------------------------------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------------------------------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=RelWithDebInfo
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------------------------------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
--------------------------------------------------------------------------------------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------------
```

**Comment by gergondet** [comment]
Hi @mitsuharu-morisawa 

This shouldn't happen, the catkin workspaces should always be created under the `SOURCE_DESTINATION` folder and mc-rtc-superbuild does not allow to set `SOURCE_DESTINATION` to a non empty folder or non superbuild folder

**Comment by gergondet** [comment]
(sorry I sent the previous message too early)

Is this the first build you are doing? Do you have files under `$HOME/workspace/src/catkin_ws/devel/`?
