### ISSUE TITLE
catkin_ws/devel/setup.sh not found

### ISSUE THREAD

**Issue by mmurooka** [mc-rtc/mc-rtc-superbuild#8]
The link file `catkin_ws/devel/setup.sh` sometimes disappears and `source catkin_ws/devel/setup.bash` fails.

In the normal case, `setup.sh` is a link file like
```bash
mmurooka@mmurooka-ThinkPad-P53:~/workspace/src/catkin_ws/devel$ ls -l setup.sh
lrwxrwxrwx 1 mmurooka mmurooka 84 12月 29 21:47 setup.sh -> /home/mmurooka/workspace/src/catkin_ws/devel/.private/catkin_tools_prebuild/setup.sh
```

However, at some point, this link file will be lost. I don't know what triggers the deletion of `setup.sh`.

**Comment by mmurooka** [comment]
catkin_data_ws uses catkin_make and catkin_ws uses catkin build (from catkin tools). Could this mixing be related to this issue? Unless there is a particular reason, I thought it would be better to use one of them (catkin build is personally preferred).

**Comment by gergondet** [comment]
I have noticed the same issue on my system and I have yet to find the root cause for this...

Is it enough to restore the link to make it work again?

It might be because I use this file to detect whether the catkin workspace has been initialized or not and maybe it's better to rely on the actual file rather than the symlink for this?

> Could this mixing be related to this issue?

I think it should be fine but indeed the disappearance only seem to happen on the catkin build folder.

**Comment by mmurooka** [comment]
> Is it enough to restore the link to make it work again?

Yes, as far as I have tried.

**Comment by tabinohito** [comment]
I tried mc-rtc-superbuild with  @TsuruMasato .
A similar file occurred same error.

`$ ls -ll /home/tako/workspace/src/catkin_ws/devel/env.sh
lrwxrwxrwx 1 tako tako 78  1月 18 12:36 /home/tako/workspace/src/catkin_ws/devel/env.sh -> /home/tako/workspace/src/catkin_ws/devel/.private/catkin_tools_prebuild/env.sh`
It is linked with the origin file.

![Screenshot from 2023-01-18 15-58-33](https://user-images.githubusercontent.com/29534522/213105102-350d81fc-2db7-407a-bad0-cf0ea88516c1.png)

`[ 54%] Performing test step for 'mc_state_observation'
Test project /home/tako/workspace/build/mc_state_observation
No tests were found!!!
[ 54%] Performing link-build-and-src step for 'mc_state_observation'
[ 54%] Completed 'mc_state_observation'
[ 55%] Built target mc_state_observation
[ 56%] Initializing catkin workspace in /home/tako/workspace/src/catkin_ws
[ 56%] Built target catkin-init-mc_rtc_ws
[ 56%] Build catkin workspace mc_rtc_ws at /home/tako/workspace/src/catkin_ws
/home/tako/workspace/src/catkin_ws/devel/env.sh: 15: .: Can't open /home/tako/workspace/src/catkin_ws/devel/setup.sh
Traceback (most recent call last):
  File "/usr/bin/catkin", line 33, in <module>
    sys.exit(load_entry_point('catkin-tools==0.9.2', 'console_scripts', 'catkin')())
  File "/usr/lib/python3/dist-packages/catkin_tools/commands/catkin.py", line 265, in main
    catkin_main(sysargs)
  File "/usr/lib/python3/dist-packages/catkin_tools/commands/catkin.py", line 260, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/lib/python3/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 258, in main
    ctx = Context.load(opts.workspace, opts.profile, opts, append=True)
  File "/usr/lib/python3/dist-packages/catkin_tools/context.py", line 256, in load
    ctx.load_env()
  File "/usr/lib/python3/dist-packages/catkin_tools/context.py", line 448, in load_env
    sticky_env = get_resultspace_environment(self.devel_space_abs, quiet=True)
  File "/usr/lib/python3/dist-packages/catkin_tools/resultspace.py", line 130, in get_resultspace_environment
    lines = subprocess.check_output(command, cwd=os.getcwd(), env=base_env, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/home/tako/workspace/src/catkin_ws/devel/env.sh /bin/bash -c "env --null"' returned non-zero exit status 127.
make[2]: *** [CMakeFiles/catkin-build-mc_rtc_ws.dir/build.make:73: catkin-stamps/mc_rtc_ws.stamp] エラー 1
make[1]: *** [CMakeFiles/Makefile2:1525: CMakeFiles/catkin-build-mc_rtc_ws.dir/all] エラー 2
make: *** [Makefile:146: all] エラー 2
`

**Comment by mmurooka** [comment]
The problem is that `setup.sh`, not `env.sh`, is missing. You can temporarily solve this problem by creating the link manually as follows
```
ln -s /home/tako/workspace/src/catkin_ws/devel/.private/catkin_tools_prebuild/setup.sh /home/tako/workspace/src/catkin_ws/devel/setup.sh
```


BTW, @tabinohito here is some information about markdown formatting.

> 独立したブロック内にコードあるいはテキストをフォーマットするには、3 重のバッククォートを使用します。

https://docs.github.com/ja/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by tabinohito** [comment]
> The problem is that setup.sh, not env.sh, is missing. You can temporarily solve this problem by creating the link manually as follows

I see now.

> BTW, @tabinohito here is some information about markdown formatting.

I think I've learned a lot.

**Comment by gergondet** [comment]
I think the commit above fixes that. It was happening when the command prefix deduced by superbuild changed (e.g. if you add the suggested lines in your environment after your first build)

Then CMake would delete the file because the command to generate it would change.

The commit uses a different approach to achieve the same thing and thus prevents the unwanted removal of the `setup.sh` script
