### ISSUE TITLE
Add option for mc_mujoco

### ISSUE THREAD

**Issue by mmurooka** [mc-rtc/mc-rtc-superbuild#9]
It would be nice to add an installation option for [mc_mujoco](https://github.com/rohanpsingh/mc_mujoco) (or create a superbuild extention for mc_mujoco).

**Comment by gergondet** [comment]
I have one locally, I have now created a collection of common extensions https://github.com/mc-rtc/superbuild-extensions

This include the mc_mujoco interface

I think it's easier to manage rather than having a myriad of superbuild extensions

**Comment by mmurooka** [comment]
@gergondet  Thank you. That extension is fine for me. I'll close this.
